name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Verify CLI functionality
        run: |
          echo "Testing CLI commands..."
          chmod +x bin/unicrn.js
          
          # Test version
          node bin/unicrn.js --version
          
          # Test help
          node bin/unicrn.js --help
          
          # Test list components
          node bin/unicrn.js list
          
          # Test list themes
          node bin/unicrn.js themes

      - name: Test CLI in clean directory
        run: |
          echo "Testing CLI initialization..."
          mkdir -p /tmp/test-cli
          cd /tmp/test-cli
          
          # Test init command
          node $GITHUB_WORKSPACE/bin/unicrn.js init
          
          # Verify files were created
          ls -la
          test -d components/ui
          test -d components/hooks
          test -f components/ui/index.ts
          test -f components/hooks/index.ts
          test -f components/unistyles.ts
          test -f index.ts
          
          # Test adding a component (dry run by checking list)
          echo "Testing component addition..."
          node $GITHUB_WORKSPACE/bin/unicrn.js list | grep -q "button"
          
          # Test adding a hook (dry run by checking list)
          echo "Testing hook listing..."
          node $GITHUB_WORKSPACE/bin/unicrn.js list | grep -q "usedisclose"
          
          echo "CLI test passed!"

      - name: Verify package structure
        run: |
          echo "Verifying package contents..."
          npm pack --dry-run
          
          # Check that all required files are included
          test -f bin/unicrn.js
          test -d lib/components/ui
          test -d lib/hooks
          test -f lib/unistyles.ts
          test -f lib/index.ts
          test -f README.md
          test -f package.json
          
          # Verify specific component files exist
          test -f lib/components/ui/Button.tsx
          test -f lib/components/ui/Card.tsx
          test -f lib/components/ui/index.ts
          
          # Verify hook files exist
          test -f lib/hooks/useDisclose.ts
          
          echo "Package structure verified!"

      - name: Check for security vulnerabilities
        run: npm audit --audit-level moderate
