name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Verify package structure
        run: |
          echo "Checking package.json..."
          cat package.json
          echo "Checking CLI executable..."
          chmod +x bin/unicrn.js
          node bin/unicrn.js --version
          echo "Checking components..."
          ls -la components/ui/

      - name: Run tests (if any)
        run: |
          # Add test command here when tests are available
          # npm test
          echo "No tests configured yet"

      - name: Build package
        run: |
          echo "Building package..."
          npm pack --dry-run

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release Comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.release.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🎉 Successfully published to NPM! Install with: `npx unicrn@latest`'
            })
