name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Verify NPM token
        run: |
          if [ -z "$NODE_AUTH_TOKEN" ]; then
            echo "❌ NPM_TOKEN secret is not set!"
            exit 1
          fi
          echo "✅ NPM token is configured"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Verify package structure
        run: |
          echo "📦 Checking package.json..."
          cat package.json
          echo ""
          echo "🔧 Checking CLI executable..."
          chmod +x bin/unicrn.js
          node bin/unicrn.js --version
          echo ""
          echo "📁 Checking components..."
          ls -la components/ui/
          echo ""
          echo "🎨 Checking unistyles.ts..."
          ls -la unistyles.ts

      - name: Run tests (if any)
        run: |
          # Add test command here when tests are available
          # npm test
          echo "⚠️  No tests configured yet"

      - name: Build and verify package
        run: |
          echo "🔨 Building package..."
          npm pack --dry-run
          echo ""
          echo "📊 Package contents will be:"
          npm pack --dry-run 2>/dev/null | grep -E '\.(js|ts|json|md)$' || true

      - name: Check if version already exists on NPM
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          
          echo "Checking if $PACKAGE_NAME@$PACKAGE_VERSION already exists..."
          
          if npm view $PACKAGE_NAME@$PACKAGE_VERSION version 2>/dev/null; then
            echo "❌ Version $PACKAGE_VERSION already exists on NPM!"
            echo "Please bump the version in package.json before releasing."
            exit 1
          else
            echo "✅ Version $PACKAGE_VERSION is available for publishing"
          fi

      - name: Publish to NPM
        run: |
          echo "🚀 Publishing to NPM..."
          npm publish --access public
          echo "✅ Successfully published to NPM!"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify publication
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          
          echo "🔍 Verifying publication..."
          sleep 30  # Wait for NPM to sync
          
          if npm view $PACKAGE_NAME@$PACKAGE_VERSION version; then
            echo "✅ Package successfully published and available on NPM!"
          else
            echo "❌ Package publication verification failed"
            exit 1
          fi

      - name: Update release with NPM publish success
        uses: actions/github-script@v7
        with:
          script: |
            const packageJson = require('./package.json');
            const version = packageJson.version;
            const name = packageJson.name;
            
            // Get the current release
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: `v${version}`
            });
            
            // Update the release body to include NPM publish success
            const npmSuccessNote = `
            
            ---
            
            ## 📦 NPM Package Published Successfully!
            
            🎉 **Package:** [\`${name}@${version}\`](https://www.npmjs.com/package/${name})
            
            **Quick Install:**
            \`\`\`bash
            npx ${name}@latest init
            \`\`\`
            
            **Global Install:**
            \`\`\`bash
            npm install -g ${name}@${version}
            \`\`\`
            
            Published at: ${new Date().toISOString()}`;
            
            // Update the release with NPM info
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              body: release.data.body + npmSuccessNote
            });
            
            console.log(`✅ Updated release with NPM publish success!`);
            console.log(`📦 Package: https://www.npmjs.com/package/${name}`);
            console.log(`🚀 Install with: npx ${name}@latest init`);
